export const productList = [
  {
    productName:"Jeans",
    productId:1,
    ProductPrice:700,
  },
  {
    productName:"Top",
    productId:2,
    ProductPrice:300,
  },
  {
    productName:"Shoes",
    productId:3,
    ProductPrice:1000,
  },
  {
    productName:"Shocks",
    productId:4,
    ProductPrice:100,
  },
  {
    productName:"Kurti",
    productId:5,
    ProductPrice:500,
  },
  {
    productName:"Cap",
    productId:6,
    ProductPrice:200,
  },
  {
    productName:"Hat",
    productId:7,
    ProductPrice:100,
  },
  {
    productName:"Watch",
    productId:8,
    ProductPrice:1200,
  }
]
